apiVersion: apps/v1
kind: Deployment
metadata:
  name: lwapp1
  labels:
    app: lwapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lwapp1
  template:
    metadata:
      labels:
        app: lwapp1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

