apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: lwapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lwapp1
  template:
    metadata:
      labels:
        app: lwapp1
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

